// <auto-generated />
namespace ShoppingSpree.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductsDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductsDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201912070008248_ProductsDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
